# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04a5410a901f5a168e4abfdc44ea60d6c49c8959bbeb0fb6e3677b8cb613a40b680df9be2ab3b7f78d03f50835bc24aa7f48f80a4fa239389828c9c3f4165a72

test:
  secret_key_base: a1297e7bd2479cb228551070a89c7616cc3582e175b5102a9733fa5efdfb1311ebfa7f6575085ba1fd37bf96ddcf9ff4c5715483d6b19eea8ac33acbfffe38eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
